baseURL = "https://example.com/"
languageCode = "en-us"
title = "Example - CV"
theme = "cv-almeida"

[params]
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorPageBackground = "#ddd"
colorRightColumnBackground = "#f5f5f5"
