baseURL = "https://example.com/"
languageCode = "en-us"
theme = "almeida-cv"
title = "Example - CV"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
