languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://example.com/"
title = "Example - CV"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#e3bfb8"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#e3bfb8"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = false
